### ISSUE TITLE
[BUG] DlConfusionMatrix - tooltip issues

### ISSUE THREAD

**Issue by Yonatan-Mesika** [dataloop-ai/components#378] opened 2023-06-01 13:48 UTC
**Describe the bug**
In some cases, the tooltip appears completely outside the matrix (very far from the pointed cell). 
Also, we have an issue with the tooltip background color (transparent in Dark mode and Almost unreadable in Light mode). 

**Expected behavior**
Should be as required in the Figma.

**Screenshots**
![image](https://github.com/dataloop-ai/components/assets/112543467/291a14ea-5208-4a58-9e2a-4445cb46ef1a)
![image](https://github.com/dataloop-ai/components/assets/112543467/c417ba9f-d281-490f-8ded-eb990d26ca6a)

**Device (please complete the following information):**
 - OS: Linux
 - Browser: Chrome
 - Version: latest

**Comment by Yonatan-Mesika** [comment] 2023-06-26 13:00
@prodan-eric 
This issue isn't resolved, we still face UI issues with the tooltips in our platform. 
Not sure why, I attached some images - please note:
1. The background is still transparent in dark mode, and almost not readable in light mode.
2. The tooltip position is drifted right, which in some cases required an x-axis scroll to see it. 

@fadiDL FYI.
![image](https://github.com/dataloop-ai/components/assets/112543467/c4b257d5-7888-4105-a387-1785a550f862)
![image](https://github.com/dataloop-ai/components/assets/112543467/09cf4867-b717-44d3-9930-2a26a9dbf68b)
![image](https://github.com/dataloop-ai/components/assets/112543467/e5637ea3-98c1-4c57-98e7-14498c71f398)
![image](https://github.com/dataloop-ai/components/assets/112543467/92b18856-3873-466b-be97-eca67746cbb8)
![image](https://github.com/dataloop-ai/components/assets/112543467/a16ae7ec-16be-44b5-8361-2b4a3c07d32d)

**Comment by fadiDL** [comment] 2023-06-26 16:57
Closing this issue as @prodan-eric found that the root cause is a style conflict coming from Platform side.

**Comment by fadiDL** [comment] 2023-06-26 16:57
Closing this issue as @prodan-eric found that the root cause is a style conflict coming from Platform side.

**Closed by fadiDL** 2023-06-26 16:57 UTC
Labels: bug
