### ISSUE TITLE
[BUG] dlButton - clicking on the padding area of a button not open insider `dlmenu`

### ISSUE THREAD

**Issue by perydataloop** [dataloop-ai/components#139] opened 2023-04-09 20:53 UTC
**Describe the bug**
when buttons have padding, clicking on the padding area does not trigger a click even on the highlights part

**To Reproduce**
1. create a button with a dlmenu inside it
``` 
   <dl-button icon="icon-dl-variable" padding="7px" flat color="dl-color-darker"
                       tooltip="Pipeline variables" size="l"            >
                <dl-menu auto-close anchor="bottom middle" self="top middle"
                        square width="200px" :offset="[0, 10]"
                        style="background: var(--dl-color-panel-background)" >
                        
                    <dl-list :padding="false" class="row" style="gap:7px">
                        <dl-list-item clickable >
                                some list text
                        </dl-list-item>
                    </dl-list>
     </dl-menu>
            </dl-button>
```
3. hover with mouse on the button but clicking **not** on the icon
4. menu is not open

**Expected behavior**
when clicking on the highlighted part of the button and not just on the icon the menu should open

**Screenshots**
![image](https://user-images.githubusercontent.com/127755482/230795950-1274cb35-f6a7-449a-85cb-5c4b07a7d632.png)

**Comment by ORily287** [comment] 2023-04-10 15:31
@perydataloop please add more information, does the event not happening? is there an erorr?
@fadiDL please see this bug and all the label

**Comment by fadiDL** [comment] 2023-04-10 15:37
What seems to occur here is the wrapper for this component does not trigger the click when clicked on the menu inside. (maybe because the menu eats the event aswell and stops it)

**Comment by perydataloop** [comment] 2023-04-10 15:45
To be clearer, the bug happens only when you try to open the menu. At first, I thought that the problem was that the button didn't have a "@click" event outside the icon element. But when I clicked a similar sibiling button nearby, it triggered the click event. So, I realized that the issue is caused by a combination of dlButtng+dlMenu.

**Comment by vadim-popa-opentech** [comment] 2023-04-12 09:31
I put your code in our repository and everything works fine. We can't reproduce this issue. 

![image](https://user-images.githubusercontent.com/127128115/231410596-47ed63dc-6c67-4389-8cbf-5820d5cda7a1.png)

**Comment by perydataloop** [comment] 2023-04-13 11:59
I digging into it a bit, try to delete all elements around, and played with the padding. also looks into the source code, and tests it on Chrome and edge.  in all cases it reproduces. I think I will take it with @fadiDL on Sunday.

**Comment by vadim-popa-opentech** [comment] 2023-04-20 12:24
@perydataloop  please let me know if I can help you more, otherwise close this issue from your side

**Comment by fadiDL** [comment] 2023-04-25 09:35
Picking this up as its also caused in OA + Vue2 issues it seems. i could sometimes reproduce with the given code. 
i will handle this issue manually

**Closed by fadiDL** 2023-04-25 09:35 UTC
Labels: bug
