### ISSUE TITLE
[BUG] {{ dl-line chart }} - {{ Ux issue }}

### ISSUE THREAD

**Issue by rotemshaham** [dataloop-ai/components#377] opened 2023-06-01 12:14 UTC
1. The range selector is not working well. 

https://github.com/dataloop-ai/components/assets/121247551/e0bed302-2c85-4244-8708-dcdb912da2dd

**Comment by VictorOpenTech** [comment] 2023-06-02 09:20
@rotemshaham, please describe in details what you'd like to change/improve: what works bad and how'd like to improve the behavior :pray:

**Comment by rotemshaham** [comment] 2023-06-05 08:49
@VictorOpenTech The range selector/zoom is not working smoothly. The grab and drag are very difficult to use.

**Comment by SorinOpt** [comment] 2023-06-05 13:59
@rotemshaham I tested, brush component works as expected, if it's too small you can make it bigger via props.

**Comment by VictorOpenTech** [comment] 2023-07-17 09:26
@fadiDL, we don't received explicit actions for the line chart from @rotemshaham 
you have an option to change the size of the brush from props, do we need to change smthng in design?

**Comment by fadiDL** [comment] 2023-07-17 11:05
@SorinOpt @VictorOpenTech there does seem to be an issue here with the size of the div we click on. from the video it does seem that rotem is clicking on the div and dragging and the dlbrush is not moving at all.

@SorinOpt if you cant reproduce this try in vue2 if neither is reproduced then pleaes close this issue 
@rotemshaham since we have a prop to handle size of the brush handlers then it can be mitigated for smaller displays or higher resolution ones on OA side.

**Closed** 2023-07-28 08:08 UTC
Labels: bug, design
