### ISSUE TITLE
[BUG] DlPopup - The horizontal offset doesn’t work

### ISSUE THREAD

**Issue by rotemshaham** [dataloop-ai/components#537] opened 2023-08-09 13:46 UTC
When using a dl-popup that is very close to the edge of the screen. 
![image (63)](https://github.com/dataloop-ai/components/assets/121247551/fa90746f-da9e-45b2-add4-1a1aa8773bab)

when giving offset [10, 10] it does not affect the popup

**Comment by fadiDL** [comment] 2023-08-14 14:22
Cannot reproduce, most likely fixed with other dl-popup fixes

**Closed by fadiDL** 2023-08-14 14:22 UTC
Labels: bug
