### ISSUE TITLE
[BUG] {{ dl smart tooltip }} - {{ UI issues }}

### ISSUE THREAD

**Issue by rotemshaham** [dataloop-ai/components#354] opened 2023-05-31 14:00 UTC
1. The issues refer to both dark & light themes. 
2. Remove the background around the tooltip (it looks like the tooltip background).
3. The buttons at the bottom are broken- should be next to each other. 
4. Buttons: The space between the icon and the text is too large. Change the gap to 6px (do not use padding) 
![Screenshot 2023-05-31 at 17 00 13](https://github.com/dataloop-ai/components/assets/121247551/682e17c0-44fc-4a3d-b777-2afc674982a0)

**Comment by VictorOpenTech** [comment] 2023-06-06 09:28
@rotemshaham the same here, we're  not able to generate the bug on DL portal, in StoryBook it works normal. @fadiDL could you assign someone from Dataloop team to take a look of this issue? :pray:

**Comment by fadiDL** [comment] 2023-07-18 14:35
Closing as it seems to work fine in both vue2 and vue3 cant reproduce the bugs

**Closed** 2023-07-18 14:35 UTC
Labels: bug, design
