### ISSUE TITLE
[FEATURE] dlSelect  - padding around dl-select are not consist with padding around dl-input

### ISSUE THREAD

**Issue by perydataloop** [dataloop-ai/components#165] opened 2023-04-17 14:58 UTC
**Describe the bug**
in dl-select, there is no default padding for the selected size ( in my test default size = m ) 

**To Reproduce**
1. Go to [ dlselect ](https://dataloop-ai.github.io/components/?path=/docs/library-components-dlselect--docs)
2. change size to 'm'
3. inspect on the element in devtool
4. See that there is no padding arround

**Expected behavior**
when I use dl-input and dl-select I expect that there padding for the same size will be the same so they align on the same row

**Screenshots**
in the screen shoot side by side dlInput and dlSelect
![image](https://user-images.githubusercontent.com/127755482/232524683-5e05b7cd-8026-499d-921b-c9dc69940c71.png)

**Comment by fadiDL** [comment] 2023-04-17 17:12
@perydataloop not a bug. this is a feature request as this was not part of the design.

Moving this to design related.

**Comment by SorinOpt** [comment] 2023-04-19 10:04
@perydataloop Adding the `dense` prop to `dl-input` will resolve this issue.  Another solution is to remove the default padding on input component, but in this case, the dense prop is useless and should be removed. @fadiDL can you please confirm which solution is most reasonable for you?

**Comment by SorinOpt** [comment] 2023-04-19 10:06
@perydataloop Adding the dense prop to dl-input will resolve this issue. Another solution is to remove the default padding on input component, but in this case, the dense prop is useless and should be removed. @fadiDL can you please confirm which solution is most reasonable for you?

**Comment by perydataloop** [comment] 2023-04-19 10:56
I prefer maintain white padding around all inputs and family of them so the
spaces in the entire app will be consistent.

For now i just use 'dense'. And if you look on other issue i opened i
prefer to make it the obvious prop for removed padding.

**Comment by SorinOpt** [comment] 2023-04-25 14:17
@Barp311, @rotemshaham  Hi, could you confirm please, should I add padding 20px by default to DlSelect and DlInput components and in which components should I add this padding also? Thank you

**Comment by Barp311** [comment] 2023-05-01 07:20
@SorinOpt i am Working on it

**Comment by VictorOpenTech** [comment] 2023-05-08 08:46
@Barp311, when have some updates, let us know please 🙏

**Comment by fadiDL** [comment] 2023-05-08 17:00
@Barp311 please reopen seperate tasks for this instead of one single issue if needed.

**Closed by fadiDL** 2023-05-08 17:00 UTC
Labels: enhancement, design
