### ISSUE TITLE
[BUG] DlTable - pagination not working

### ISSUE THREAD

**Issue by perydataloop** [dataloop-ai/components#120] opened 2023-04-04 10:28 UTC
**Describe the bug**
1) when a user clicks on a page button the out `pagination` object that is provided to the table is not updated. 
2) when page's button are clicked the whole table are emptied from rows , an empty message showed and pagination component disappears. so user can go back
2) buttons of pages have no limit and can go out from the screen 

**To Reproduce**
1. go to demo page  `DlTableDemo.vue` 
2. add  above the table 
```
<div>
    pagination: {{pagination}}
</div>
```
3. add `:pagination="pagination"` to dl-table line 99
4. add `pagination` to `defineComponent.data` line 306
```
   pagination: {
                rowsPerPage: 15,
                rowsNumber: 700, /*todo: this is not working*/
                page: 1
            },
```
5. to to `https://local.dataloop.ai:8443/projects/a8ca8dc3-52d5-499d-a9b3-307a05ab2f54/components` 
6. navigate to table in the side pannel 
7. you should show the drop of navigation object above the table
8. click on `2` in the  navigation 
9. see that the drop of the `pagination` are not change. 
10. click on `27` in the navigation
11. see the all table collapse to empty table

**Expected behavior**
1) when I click on page I expect to see the pagination object update with the new page
2) when I click on page out of the date range I expect to see table in full size like 15 row are present with some loading animation 
until data will be fetched and filled with the missing data. 
3) also I expect that the internal memo of the table will now how to handle the memo of each page so it know for example that pages 1,2 and 27 exist and all other pages are missings

**Screenshots**
initial state
![image](https://user-images.githubusercontent.com/127755482/229763923-e1f1924f-ffd0-433c-b349-2cd207536a85.png)
after clicking on page 2 ( drop not change ) 
![image](https://user-images.githubusercontent.com/127755482/229764135-1a133c62-527a-41a5-864c-3586a0273625.png)
after clicking on 27 ( whole table collapse to empty table ) 
![image](https://user-images.githubusercontent.com/127755482/229764279-84e9bced-3b77-4fe3-a6b9-2a31d56fd0a9.png)

**Additional context**
dl-compoent: "version": "0.16.7",

**Comment by ORily287** [comment] 2023-04-04 14:52
@perydataloop if this is not a bug please make sure to remove

**Comment by SorinOpt** [comment] 2023-04-05 15:40
@Yonatan-Mesika @ORily287  fixed on [PR131](https://github.com/dataloop-ai/components/pull/131)

**Closed** 2023-04-06 14:18 UTC
Labels: bug
